<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABStock.AI\ABStock.AI.csproj" />
    <ProjectReference Include="..\ABStock.Application\ABStock.Application.csproj" />
    <ProjectReference Include="..\ABStock.Persistence\ABStock.Persistence.csproj" />
  </ItemGroup>

</Project>
